Feat/start ci
acesso-io/unico-check-flutter pull request #21
Opened 2021-08-30 20:05 UTC by Diniz-Lucas

### Why?
> Start ci 

### Changes
> add files

### How to test
-

### Preview
-

### Issues
https://github.com/acesso-io/squad-check-mobile/issues/105

2021-08-30 20:39 UTC, henrique-cocito requested changes

2021-08-30 20:39 UTC, henrique-cocito commented on .github/workflows/on_merge.yaml
> +  Test:
it's better to make this name lowercase

2021-08-30 20:39 UTC, henrique-cocito commented on .github/workflows/on_pull_request.yaml
> +  Test:
same here

2021-08-30 20:53 UTC, beatrizmonteiromendes approved these changes

2021-08-31 13:32 UTC, lucas-ibiapina submitted a review, later dismissed
LGTM

2021-08-31 14:00 UTC, henrique-cocito approved these changes

2021-08-31 14:01 UTC, henrique-cocito approved these changes

2021-08-31 14:06 UTC, lucas-ibiapina approved these changes

2021-08-31 14:07 UTC, merged