feat: update andrdoid ios 3.0.2
acesso-io/unico-check-flutter pull request #53
Opened 2022-11-16 18:25 UTC by Diniz-Lucas

### Why?
> 
feat: Update android 4.2.0 and ios 2.3.7
fix: Document example 

### Changes
> build.gradle, Podfile.lock and Main.dart

### How to test
> flutter test

### Preview
> A screenshot to show what this change does (optional)

### Issues
> 
https://unicoidtech.atlassian.net/browse/SD-190
https://unicoidtech.atlassian.net/browse/SD-220
https://unicoidtech.atlassian.net/browse/SD-221

2022-11-16 18:28 UTC, squad-coreeng-appsec-eng commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [f34ce43f\-8d7f\-4405\-b4f1\-8811219c9f7f](https://ast.checkmarx.net/projects/918db732-ffa3-4b08-b962-ae9c1f7a3989/scans?id=f34ce43f-8d7f-4405-b4f1-8811219c9f7f&branch=feat%2Fupdate-andrdoid-ios-3.0.2)
### No New Or Fixed Issues Found

2022-11-16 18:33 UTC, MatheusDomingos requested changes

2022-11-16 18:33 UTC, MatheusDomingos commented on android/build.gradle
> +    implementation 'com.github.acesso-io:acessobio-android:4.2.5'
this version is broken for versions <= than android 7.

2022-11-23 18:00 UTC, Diniz-Lucas commented on android/build.gradle
> +    implementation 'com.github.acesso-io:acessobio-android:4.2.5'
solved

2022-11-23 20:34 UTC, vitorherrmann-unico approved these changes

2022-11-23 21:03 UTC, MatheusDomingos approved these changes

2022-11-23 21:16 UTC, merged